# Link: https://www.hackerrank.com/candidates/82cngd9g7f2?b=eyJ1c2VybmFtZSI6ImhzaWFvdGluZzA5MTlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIyODQwNzlhMyIsImhpZGUiOnRydWUsImhpZGVTd2l0Y2hBY2NvdW50IjpmYWxzZSwiaGlkZVNoYXJlSGFja2VyUHJvZmlsZSI6ZmFsc2UsImFjY29tbW9kYXRpb25zIjpudWxsfQ==&utm_campaign=candidate-portal-v1&utm_content=6hlc6c94q7s&utm_medium=api&utm_source=v3_api_invited&utm_term=invite

